Repository HyperloopUPV-H8/ST-LIB, pull requests merged in 2022-10, with the labels that each got.

#6 Referencia a Hyperlib y otros problemas menores solucionados
  .cproject
  .project
  .settings/language.settings.xml
Labels: bug

#15 Features/flash
  .cproject
  Inc/HALAL/Services/Flash/Flash.hpp
  Inc/HALAL/Services/Flash/FlashTests/Flash_Test.hpp
  Inc/ST-LIB.hpp
  Src/HALAL/Services/Flash/Flash.cpp
  Src/HALAL/Services/Flash/FlashTests/Flash_Test.cpp
Labels: enhancement

#19 Features/adc service
  Inc/HALAL/Models/PinModel/Pin.hpp
  Inc/HALAL/Services/ADC/ADC.hpp
  Inc/ST-LIB.hpp
  Src/HALAL/Services/ADC/ADC.cpp
Labels: enhancement

#20 Fixed some errors in DigitalInput/Output
  Inc/HALAL/Services/DigitalInput/DigitalInput.hpp
  Inc/HALAL/Services/DigitalOutput/DigitalOutput.hpp
  Src/HALAL/Services/DigitalInput/DigitalInput.cpp
  Src/HALAL/Services/DigitalOutput/DigitalOutput.cpp
Labels: bug

#21 [NO MERGE] Gitignore important update
  .gitignore
  .settings/language.settings.xml
Labels: bug, enhancement

#23 Features/cproject fix
  .cproject
  .settings/stm32cubeide.project.prefs
  Inc/HALAL/Models/PinModel/Pin.hpp
  Inc/HALAL/Services/ADC/ADC.hpp
  Inc/HALAL/Services/DigitalInput/DigitalInput.hpp
  Inc/HALAL/Services/DigitalOutput/DigitalOutput.hpp
  Inc/HALAL/Services/Flash/Flash.hpp
  Inc/HALAL/Services/Flash/FlashTests/Flash_Test.hpp
  Inc/HALAL/Services/PWM/PWM.hpp
  Inc/ST-LIB.hpp
  Src/HALAL/Models/PinModel/Pin.cpp
  Src/HALAL/Services/ADC/ADC.cpp
  Src/HALAL/Services/DigitalInput/DigitalInput.cpp
  Src/HALAL/Services/DigitalOutput/DigitalOutput.cpp
  Src/HALAL/Services/Flash/Flash.cpp
  Src/HALAL/Services/PWM/PWM.cpp
Labels: bug
