Repository HyperloopUPV-H8/ST-LIB, pull requests merged in 2023-02, with the labels that each got.

#182 Now only one parameter is necesary to call ErrorHandler
  Inc/C++Utilities/CppUtils.hpp
  Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp
  Src/ST-LIB_LOW/ErrorHandler/ErrorHandler.cpp
Labels: bug

#181 Fix/input capture start fix
  Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
  Inc/HALAL/Services/InputCapture/InputCapture.hpp
  Src/HALAL/Models/TimerPeripheral/TimerPeripheral.cpp
  Src/HALAL/Services/InputCapture/InputCapture.cpp
Labels: bug

#186 xD
  Src/HALAL/Models/TimerPeripheral/TimerPeripheral.cpp
Labels: bug

#184 Fix/time
  Src/HALAL/Services/Time/Time.cpp
Labels: bug

#188 Cambios necesarios para hacer funcionar el ethernet en el template project
  Inc/HALAL/Models/IPV4/IPV4.hpp
  Inc/HALAL/Services/Communication/Ethernet/Ethernet.hpp
  Inc/HALAL/Services/Communication/Ethernet/EthernetNode.hpp
  Inc/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.hpp
  Inc/HALAL/Services/Communication/Ethernet/TCP/Socket.hpp
  Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp
  Src/HALAL/Services/Communication/Ethernet/EthernetNode.cpp
  Src/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.cpp
  Src/HALAL/Services/Communication/Ethernet/TCP/Socket.cpp
Labels: bug

#140 ST-LIB Start
  .gitignore
  Inc/HALAL/HALAL.hpp
  Inc/HALAL/Models/HALconfig/HALconfig.hpp
  Inc/HALAL/Models/IPV4/IPV4.hpp
  Inc/HALAL/Services/Communication/Ethernet/Ethernet.hpp
  Inc/HALAL/Services/Communication/SPI/SPI.hpp
  Inc/HALAL/Services/Communication/UART/UART.hpp
  Inc/HALAL/Services/PWMService/PWMService.hpp
  Inc/ST-LIB.hpp
  Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp
  Inc/ST-LIB_LOW/ST-LIB_LOW.hpp
  Src/HALAL/HALAL.cpp
  Src/HALAL/Models/HALconfig/Halconfig.cpp
  Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp
  Src/HALAL/Services/Communication/SPI/SPI.cpp
  Src/ST-LIB.cpp
  Src/ST-LIB_LOW/ST-LIB_LOW.cpp
Labels: enhancement

#193 Fix/timer peripheral fix
  Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
  Inc/ST-LIB_LOW/Actuator/HalfBridge/HalfBridge.hpp
  Src/HALAL/Models/PinModel/Pin.cpp
  Src/HALAL/Models/TimerPeripheral/TimerPeripheral.cpp
  Src/ST-LIB_LOW/Actuator/HalfBridge/HalfBridge.cpp
Labels: bug

#200 All error handler added
  Inc/HALAL/Services/Encoder/Encoder.hpp
  Src/HALAL/Services/Encoder/Encoder.cpp
Labels: enhancement

#197 Fix/fix pin print
  Inc/HALAL/Models/PinModel/Pin.hpp
  Src/HALAL/Models/PinModel/Pin.cpp
  Src/HALAL/Services/PWMService/PWMService.cpp
  Src/ST-LIB_LOW/Actuator/PWM/PWM.cpp
  Src/ST-LIB_LOW/Sensors/DigitalSensor/DigitalSensor.cpp
  Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
  Src/ST-LIB_LOW/Sensors/LinearSensor/LinearSensor.cpp
  Src/ST-LIB_LOW/Sensors/LookupSensor/LookupSensor.cpp
  Src/ST-LIB_LOW/Sensors/SensorInterrupt/SensorInterrupt.cpp
Labels: bug

#196 Fix/fdcan error handler fix
  Src/HALAL/Services/Communication/FDCAN/FDCAN.cpp
Labels: bug

#194 STLIB update
  Inc/ST-LIB.hpp
  Src/ST-LIB.cpp
Labels: enhancement

#198 Fix/spi error handler
  Inc/HALAL/Services/Communication/SPI/SPI.hpp
  Src/HALAL/Services/Communication/SPI/SPI.cpp
Labels: enhancement

#208 Adapted FDCAN for bootloader
  Inc/HALAL/Services/Communication/FDCAN/FDCAN.hpp
  Inc/ST-LIB_HIGH/Protections/Protection.hpp
  Src/HALAL/Models/HALconfig/Halconfig.cpp
  Src/HALAL/Services/Communication/FDCAN/FDCAN.cpp
Labels: bug

#211 Added Packet Destructor
  Inc/HALAL/Models/Packets/Packet.hpp
Labels: bug

#209 Hot Fix
  Inc/HALAL/Models/Packets/Packet.hpp
  Inc/HALAL/Models/PinModel/Pin.hpp
  Inc/HALAL/Services/ADC/ADC.hpp
  Inc/HALAL/Services/Communication/FDCAN/FDCAN.hpp
  Inc/HALAL/Services/Communication/SPI/SPI.hpp
  Inc/HALAL/Services/EXTI/EXTI.hpp
  Inc/ST-LIB_HIGH/Protections/Protection.hpp
  Src/HALAL/Models/HALconfig/Halconfig.cpp
  Src/HALAL/Models/PinModel/Pin.cpp
  Src/HALAL/Models/TimerPeripheral/TimerPeripheral.cpp
  Src/HALAL/Services/ADC/ADC.cpp
  Src/HALAL/Services/Communication/Ethernet/TCP/Socket.cpp
  Src/HALAL/Services/Communication/FDCAN/FDCAN.cpp
  Src/HALAL/Services/EXTI/EXTI.cpp
  Src/ST-LIB_HIGH/Protections/Protection.cpp
Labels: bug

#215 Fixed Ethernet start and inscribe methods
  Src/HALAL/HALAL.cpp
  Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp
  Src/ST-LIB.cpp
Labels: bug, help wanted

#212 Decimal PWM and variable frequency
  Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
  Inc/HALAL/Services/PWMService/PWMService.hpp
  Inc/ST-LIB_LOW/Actuator/PWM/PWM.hpp
  Src/HALAL/Models/TimerPeripheral/TimerPeripheral.cpp
  Src/HALAL/Services/PWMService/PWMService.cpp
  Src/ST-LIB_LOW/Actuator/PWM/PWM.cpp
Labels: enhancement

#213 Nested state machines
  Inc/C++Utilities/CppUtils.hpp
  Inc/HALAL/Services/Time/Time.hpp
  Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
  Src/ST-LIB_LOW/StateMachine/StateMachine.cpp
Labels: enhancement
