Repository HyperloopUPV-H8/ST-LIB, pull requests merged in 2023-01, with the labels that each got.

#128 supress warnings
  .cproject
  Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h7xx.h
  Drivers/CMSIS/Include/core_cm7.h
  Drivers/CMSIS/Include/mpu_armv7.h
  Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_ll_adc.h
  Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
  Src/HALAL/Services/InputCapture/InputCapture.cpp
Labels: enhancement

#87 Features/dma init
  Inc/HALAL/Models/DMA/DMA.hpp
  Src/HALAL/Models/DMA/DMA.cpp
Labels: enhancement

#129 LPTIM INIT function
  .settings/language.settings.xml
  Inc/HALAL/Models/LowPowerTimer/LowPowerTimer.hpp
  Src/HALAL/Models/LowPowerTimer/LowPowerTimer.cpp
  Src/HALAL/Models/Runes/Runes.cpp
  Src/HALAL/Services/ADC/ADC.cpp
Labels: enhancement

#132 explicit std usages
  Inc/C++Utilities/CppUtils.hpp
Labels: bug, enhancement

#124 Rework/spi fix
  Inc/HALAL/Services/Communication/SPI/SPI.hpp
  Src/HALAL/Services/Communication/SPI/SPI.cpp
Labels: bug, enhancement

#138 update UART to use spans
  Inc/HALAL/Services/Communication/UART/UART.hpp
  Src/HALAL/Services/Communication/UART/UART.cpp
Labels: bug, enhancement

#143 Features/error handler
  Inc/C++Utilities/CppUtils.hpp
  Inc/HALAL/Models/Packets/PacketValue.hpp
  Inc/HALAL/Services/Communication/Ethernet/UDP/DatagramSocket.hpp
  Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp
  Inc/ST-LIB_LOW/ST-LIB_LOW.hpp
  Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
  Middlewares/Third_Party/LwIP/src/include/lwip/opt.h
  Src/HALAL/Models/IPV4/IPV4.cpp
  Src/HALAL/Models/Packets/Packet.cpp
  Src/HALAL/Models/Runes/Runes.cpp
  Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp
  Src/HALAL/Services/Communication/Ethernet/UDP/DatagramSocket.cpp
  Src/HALAL/Services/Communication/UART/UART.cpp
  Src/ST-LIB_LOW/ErrorHandler/ErrorHandler.cpp
Labels: enhancement

#142 math+cordic bug solving
  Inc/HALAL/HALAL.hpp
  Inc/HALAL/Services/CORDIC/CORDIC.hpp
  Inc/ST-LIB_LOW/Math/Math.hpp
  Src/HALAL/Services/CORDIC/CORDIC.cpp
  Src/ST-LIB_LOW/Math/Math.cpp
Labels: bug

#141 Fix ADC3 not working
  Src/HALAL/Services/ADC/ADC.cpp
Labels: bug

#137 Features/sensor start
  Inc/ST-LIB_LOW/Sensors/DigitalSensor/DigitalSensor.hpp
  Inc/ST-LIB_LOW/Sensors/LinearSensor/LinearSensor.hpp
  Inc/ST-LIB_LOW/Sensors/LookupSensor/LookupSensor.hpp
  Inc/ST-LIB_LOW/Sensors/Sensor/Sensor.hpp
  Src/ST-LIB_LOW/Sensors/DigitalSensor/DigitalSensor.cpp
  Src/ST-LIB_LOW/Sensors/LinearSensor/LinearSensor.cpp
  Src/ST-LIB_LOW/Sensors/LookupSensor/LookupSensor.cpp
  Src/ST-LIB_LOW/Sensors/Sensor/Sensor.cpp
Labels: enhancement

#144 create makefile
  .gitignore
  CMakeLists.txt
  Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h7xx.h
Labels: enhancement

#159 include adc guards
  Inc/HALAL/Services/ADC/ADC.hpp
  Src/HALAL/Services/ADC/ADC.cpp
Labels: bug

#154 remove runes
  Src/HALAL/Models/Runes/Runes.cpp
Labels: bug, enhancement

#161 Removed stlib include in UART
  Inc/HALAL/Services/Communication/UART/UART.hpp
Labels: bug

#160 ErrorHandler bug fix
  Inc/C++Utilities/CppUtils.hpp
  Inc/HALAL/HALAL.hpp
  Inc/HALAL/Models/IPV4/IPV4.hpp
  Inc/HALAL/Services/Communication/Ethernet/EthernetNode.hpp
  Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp
  Src/ST-LIB_LOW/ErrorHandler/ErrorHandler.cpp
Labels: bug

#167 DigitalOutput Toggle
  Inc/HALAL/Services/DigitalOutputService/DigitalOutputService.hpp
  Inc/ST-LIB_LOW/Actuator/DigitalOutput/DigitalOutput.hpp
  Inc/ST-LIB_LOW/ST-LIB_LOW.hpp
  Src/HALAL/Services/ADC/ADC.cpp
  Src/HALAL/Services/DigitalOutputService/DigitalOutputService.cpp
  Src/HALAL/Services/EXTI/EXTI.cpp
  Src/HALAL/Services/InputCapture/InputCapture.cpp
  Src/ST-LIB_LOW/Actuator/DigitalOutput/DigitalOutput.cpp
Labels: enhancement

#166 Added to_string method to Pin
  Inc/HALAL/Models/PinModel/Pin.hpp
  Src/HALAL/Models/PinModel/Pin.cpp
Labels: enhancement

#169 features/ErrorHandlerPin
  Inc/ST-LIB_LOW/ST-LIB_LOW.hpp
  Src/HALAL/Models/PinModel/Pin.cpp
Labels: enhancement

#172 Fix de la ST-LIB, runes y el template project.
  Inc/HALAL/Services/ADC/ADC.hpp
  Src/HALAL/Models/PinModel/Pin.cpp
  Src/HALAL/Services/Communication/SPI/SPI.cpp
  Src/HALAL/Services/Communication/UART/UART.cpp
Labels: bug

#168 PWM Error Handler
  Src/HALAL/Services/PWMService/PWMService.cpp
  Src/ST-LIB_LOW/Actuator/PWM/PWM.cpp
Labels: enhancement

#177 fix PWM error
  Src/HALAL/Services/PWMService/PWMService.cpp
  Src/ST-LIB_LOW/Actuator/PWM/PWM.cpp
Labels: bug

#174 Encoder Fix
  Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
  Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
Labels: bug

#180 Fix/handle errors in timer peripheral
  Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
  Src/HALAL/Models/TimerPeripheral/TimerPeripheral.cpp
  Src/HALAL/Services/InputCapture/InputCapture.cpp
Labels: bug
